### ISSUE TITLE
missing main entry

### ISSUE THREAD

**Issue by arlac77** [gr2m/universal-user-agent#23] opened 2019-09-04 20:31 UTC
since version 4.0.0 rollup picks the browser.js instead of node.js

maybe package main entry got lost in 34fedffe22be8600dc48559f4309715ef6411393 ?

**Comment by gr2m** [comment] 2019-09-04 21:08
Hmm ... the `package.json` file in the project root is not published, instead this project is build with pika into a `pkg/` folder which then is published. The published `package.json` has a `"main"` field for node: https://unpkg.com/browse/universal-user-agent@4.0.0/package.json

But also a `"module"` field which points to the browser version. I wasn't aware that folks would use that for Node, too?

**Comment by gr2m** [comment] 2019-09-04 21:10
I just made double sure that at least `require`-ing in node is still working as expected:
https://runkit.com/gr2m/gr2m-universal-user-agent-23

**Comment by gr2m** [comment] 2019-09-04 21:16
Any idea how to resolve problem? What would the published `package.json` look like, ideally?

**Comment by arlac77** [comment] 2019-09-04 21:52
There two degrees of freedom
- content
  - browser
  - node
- package format
  - esm
  - require ? 

And only there entry points 

- browser
- main
- module

Let me dig around
the [rollup-plugin-node-resolve ](https://github.com/rollup/rollup-plugin-node-resolve) plugin
to find other modules with the same pattern (esm module(s) either for browser or node)

How is this handled in the other @octokit modules ?

For my node cli app I want to pick node/esm (through @octokit/rest)

**Comment by gr2m** [comment] 2019-09-04 22:00
> How is this handled in the other @octokit modules ?

Hmm the other Octokit modules mostly work the same in both Node & browser, with the exception of https://github.com/octokit/auth-app.js/ which is using the browser's WebCrypto API and for Node it's using the `jsonwebtoken` package

I did not yet migrate all @octokit modules, but soon all of them will be built with https://github.com/pikapkg/pack and will have the separate builds for node (using `require`) and browsers (using `import`).

Pika also distributes a `dist-src` folder, maybe that will work for you? Try to import `universal-user-agent/dist-src` (See published code here: https://unpkg.com/browse/universal-user-agent@4.0.0/dist-src/)

**Comment by arlac77** [comment] 2019-09-04 22:08
The problem is I am only using

```js
import octokit from "@octokit/rest";
```

**Comment by gr2m** [comment] 2019-09-04 22:14
Ah got it. Hmmm I really don't know, but I hope we find a solution for this. I asked the folks from Pika on twitter, maybe they have an idea what to do: https://twitter.com/gr2m/status/1169357730944958464

**Comment by arlac77** [comment] 2019-09-05 07:41
when declaring universal-user-agent as external in rollup i am able to select the node content out of the package (even through @octokit/rest).
But then there is the breaking change between 3.0.0 and 4.0.0 (default export vs named export) which is not reflected in @octokit/rest

**Comment by gr2m** [comment] 2019-09-06 00:34
It should be as of `v16.28.9`: https://github.com/octokit/rest.js/pull/1460

**Comment by schof** [comment] 2019-09-15 14:06
@arlac77 I'm trying to use `@octokit/rest` in node but running into similar problems as you. I'm using webpack and I'm excluding `universal-user-agent` from the build but AWS Lambda is still trying to load it:

> Runtime.ImportModuleError: Error: Cannot find module 'universal-user-agent'

I'm using the latest `@octokit/rest` but no luck. Any ideas?

**Comment by arlac77** [comment] 2019-09-15 17:24
@schof I have no solution only a workaround my list of to be excluded modules (rollup) gets longer and longer.

```js
// rollup.config.js

const external = [
  ...builtins,
  "universal-user-agent",
  "@octokit/rest",
  "node-fetch"
];
```

**Comment by schof** [comment] 2019-09-15 20:14
@arlac77 I tried the same thing you are doing with similar results. Ultimately I got things working by not excluding anything and monkey patching the `universal-user-agent` library. Webpack allows you to specify multiple locations for your node file - perhaps roll up will allow you to do something similar?

```javascript
resolve: {
  // Monkey patch to resolve https://github.com/mobileposse/neptune/issues/296
  modules: [path.resolve(__dirname, 'build/src/monkey-patch'), 'node_modules'],
  extensions: ['.tsx', '.ts', '.js']
}
  ```

then i took the `index.js` contents from the `universal-user-agent` package and dropped it into `build/src/monkey-patch` directory:

```
'use strict'

Object.defineProperty(exports, '__esModule', { value: true })

function _interopDefault(ex) {
  return ex && typeof ex === 'object' && 'default' in ex ? ex['default'] : ex
}

var osName = _interopDefault(require('os-name'))

function getUserAgent() {
  try {
    return `Node.js/${process.version.substr(1)} (${osName()}; ${process.arch})`
  } catch (error) {
    if (/wmic os get Caption/.test(error.message)) {
      return 'Windows <version undetectable>'
    }

    throw error
  }
}

exports.getUserAgent = getUserAgent
```

Hope that helps. Good luck!

**Comment by gr2m** [comment] 2019-09-15 21:05
I’m sorry this is causing so much headache, I hope we find a simpler solution that I can apply to the libraries, universal-user-agent is not the only one that is published this way

**Comment by FredKSchott** [comment] 2019-09-20 17:17
Hey yall, sorry for the delay jumping into this! Happy to help where i can. @arlac77 sounds like you summed it up pretty well, we have a 2x2 matrix and only 3 entrypoints to represent them with. On top of that, "module" has a real frontend focus at this point, since web bundlers are primarily the only real environment that they are expected to be used in. 

The result is that "Node ESM" is relatively unsupported, given that the official plan is for Node to move to: `type: "module", main: "index.mjs"`. But until then, there really is no good way to use ESM on Node.js.

Like @gr2m I'm still not sure I understand what situation is wanting you to use rollup inside of Node. Are you trying to bundle a Node application into a single JS file? If so, Webpack would probably be a better fit since it's much more Common.js dependent & reliant. https://github.com/zeit/ncc & https://github.com/zeit/pkg may also be good options for you.

If you really do need to use Rollup, have you tried the latest version of https://github.com/rollup/rollup-plugin-node-resolve ? Its most recent syntax allows you to define either `mainFields: ['main', 'module']` (to prefer main over module) or `mainFields: ['main']` (to only read from main). That could solve your problem as well.

**Comment by maplesteve** [comment] 2019-09-23 17:30
@FredKSchott, @gr2m : The `@octokit/rest` library just doesn't work anymore in a nodeJS environment (Lambda) after the 4.0 release - also when webpack is used. It just crashes with `module initialization error: ReferenceError`.
Our CI/CD tooling completely stopped working since then and a downgrade of `@octokit/rest` doesn't seem to work, since the other octokit dependencies also use the v4.

**Comment by gr2m** [comment] 2019-09-23 18:11
@maplesteve There must be a way in webpack to workaround this, like there is in rollup as mentioned by @FredKSchott. It's not something that I can fix in Octokit itself, I'm afraid.

But people keep running into this so I'd love to address it in the READMEs.

**Comment by gr2m** [comment] 2019-09-23 18:30
@maplesteve @schof @arlac77  

Could you please try to directly edit `node_modules/universal-user-agent/package.json` and add `"type": "commonjs"` to it, and see if that resolves the issue?

Also, could you please setup a repository with the most minimal build setup that reproduces the problem for you? I would appreciate to have both a setup using webpack and rollup.

Let's fix this 💪

**Comment by gr2m** [comment] 2019-09-23 18:32
There is also a new "exports" field that might work:
https://nodejs.org/api/esm.html#esm_package_exports

I've asked on the twitters and Myles shared some helpful links:
https://mobile.twitter.com/gr2m/status/1176199758127362048

**Comment by arlac77** [comment] 2019-09-23 19:00
Here a starting point showing rollup selecting browser content by default and the 'external' workaround to exclude 'universal-user-agent' from bundling

[arlac77/universal-user-agent-bundler-problems](https://github.com/arlac77/universal-user-agent-bundler-problems)

**Comment by FredKSchott** [comment] 2019-09-23 19:02
I’m starting to think this may be a Lambda misconfiguration/issue, If they’re using webpack internally there’s a configuration for this that they could probably set to solve for this: https://webpack.js.org/configuration/resolve/#resolvealiasfields

**Comment by maplesteve** [comment] 2019-09-23 19:37
@gr2m 
Adding `"type": "commonjs"` yields the same error:

```
"errorType":"ReferenceError", 
"stackTrace": ["ReferenceError: navigator is not defined","at getUserAgent
(webpack:///./node_modules/universal-user-agent/dist-web/index.js?:4:5)","at eval
(webpack:///./node_modules/@octokit/endpoint/dist-web/index.js?:364:126)","at
Module../node_modules/@octokit/endpoint/dist-web/index.js
```

**Comment by maplesteve** [comment] 2019-09-23 19:38
@FredKSchott regarding Lambda: "they" in terms of AWS are doing nothing with webpack. Webpack is used to bundle the code which then gets uploaded and used in the Lambda environment. It worked before.

**Comment by gr2m** [comment] 2019-09-23 19:53
@maplesteve I found https://github.com/netlify/netlify-lambda/issues/138 which sounds similar to yuor probelem. See their fix at https://github.com/netlify/netlify-lambda/pull/160/files. It looks like `webpack` is prefering the `browser` field over `module` and `main` which is causing the problem. In the case of universal-user-agent, you might need to set it to just `main` or `["main", "module"]`. Could you give that a try?

I think [Shawn summerizes](https://github.com/netlify/netlify-lambda/issues/138#issuecomment-483890015) the problem pretty well

>  this is unfortunately just a result of us using webpack for something it wasn't strictly designed to do

**Comment by FredKSchott** [comment] 2019-09-23 20:24
@maplesteve ah gotcha, I’d misunderstood. If you own the webpack config / are running webpack yourself, hopefully that resolveAlias config option fixes thing

**Comment by maplesteve** [comment] 2019-09-23 20:35
@gr2m 

The webpack changes according to the netlify issue did not help.

I created a repo to reproduce: https://github.com/maplesteve/navigator-error

**Comment by gr2m** [comment] 2019-09-23 20:50
Can you please try to set `resolveAlias` as suggested by Fred? I'd try this

```js
module.exports = {
  resolve: {
    aliasFields: []
  }
};
```

**Comment by maplesteve** [comment] 2019-09-23 21:41
@gr2m tried your suggestion re: `aliasFields` and also some other values ('browser', 'commonjs'...) but still get the same error. The source still references e.g. `@octokit/request/dist-web/index.js` where IMO it should pick `@octokit/request/dist-node/index.js`

**Comment by 1138-4EB** [comment] 2019-09-23 23:41
> Also, could you please setup a repository with the most minimal build setup that reproduces the problem for you? I would appreciate to have both a setup using webpack and rollup.
> 
> Let's fix this 💪

I think I hit this issue when trying to add webpack to the [actions/typescript-action](https://github.com/actions/typescript-action) template. This is a minimal `main.ts`:

```ts
//import * as github from '@actions/github';
const github = require('@actions/github');

export async function run() {
  try {
    console.log("HELLO WEBPACK!");

    var slug = ['user','repo']
    if (github.context.payload.repository && github.context.payload.repository.full_name) {
        slug = github.context.payload.repository.full_name.split('/')
    }
  }

  catch (error) {
    throw error;
  }
}

run();
```

And the `webpack.config.js`:

```js
const join = require('path').join;
module.exports = {
	entry: './dist/main.js',
	target: 'node',
	output: {
		path: join(__dirname, 'dist'),
		filename: 'main.pack.js'
	},
	optimization: {
		minimize: false
	},
	devtool: 'sourcemap'
};
```

Either requiring or importing `@actions/github` adds the following to `main.pack.js`:

```js
/***/ "./node_modules/universal-user-agent/dist-web/index.js":
/*!*************************************************************!*\
  !*** ./node_modules/universal-user-agent/dist-web/index.js ***!
  \*************************************************************/
/*! exports provided: getUserAgent */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "getUserAgent", function() { return getUserAgent; });
function getUserAgent() {
    return navigator.userAgent;
}
```

**Comment by sokra** [comment] 2019-09-24 05:45
> The published package.json has a "main" field for node: https://unpkg.com/browse/universal-user-agent@4.0.0/package.json

> But also a "module" field which points to the browser version.

Using the `module` field for a browser version is not correct. `module` only indicates the package format esm.

Only the `browser` field indicates a browser version.

You can map all variants to files with both fields:

``` js
"main": "node-cjs.js",
"module": "node-esm.js",
"browser": {
  "node-cjs.js": "web-cjs.js",
  "node-esm.js": "web-esm.js"
}
```

**Comment by maplesteve** [comment] 2019-09-24 21:49
@gr2m:  I understand the analysis of @sokra means, that this has to be done in the `universal-user-agent` package, correct?

**Comment by gr2m** [comment] 2019-09-24 21:59
@sokra Thanks Tobias, that makes sense.
@maplesteve  I will give it a try. I have to check in with @FredKSchott to see if this will still work with [pika.dev](https://www.pika.dev/)

**Comment by gr2m** [comment] 2019-09-25 23:56
I created a repository to explore the idea mentioned above:
https://github.com/gr2m/universal-publish-test

It has two packages: `@gr2m/universal-dependency` and `@gr2m/universal-sub-dependency`. I've added two examples for rollup with node & browser targets.

@maplesteve could you maybe add a minimal example similar to https://github.com/gr2m/universal-publish-test/tree/master/rollup-node-test without the Serverless modules and Typescript? 

I could not yet test if it works with @pikapkg because the packages don't seem to be building? 

- https://pkg.fyi/@gr2m/universal-dependency
- https://pkg.fyi/@gr2m/universal-sub-dependency

@FredKSchott could you please check if it's something on my side or an error on Pika's? 🙏 

For Pika, I think I could try to build and submit two new plugins:

- `@pika/plugin-build-universal`
- `@pika/plugin-bundle-universal`

That would follow the structure suggested above. What do you think @FredKSchott? Would that still work with the automated bundle builds for Pika CDN?

**Comment by maplesteve** [comment] 2019-09-26 09:45
> add a minimal example similar to https://github.com/gr2m/universal-publish-test/tree/master/rollup-node-test without the Serverless modules and Typescript?

@1138-4EB posted a simpler example you can use.

Maybe, the easiest way to solve this, is to just revert the change to pika, since this seems to be the root problem. The GitHub-SDK (octokit) is broken for a lot of people for nearly a week because of this.

**Comment by 1138-4EB** [comment] 2019-09-26 10:09
> > add a minimal example similar to [gr2m/universal-publish-test:rollup-node-test@`master`](https://github.com/gr2m/universal-publish-test/tree/master/rollup-node-test) [](/gr2m/universal-publish-test/tree/HEAD@{2019-09-26T09:45:15Z}/rollup-node-test) without the Serverless modules and Typescript?
> 
> @1138-4EB posted a simpler example you can use.

Note that the simple example [above](https://github.com/gr2m/universal-user-agent/issues/23#issuecomment-534326642) requires to execute `tsc` before `webpack`. This other project uses the same base, but the entry is set to `main.ts` and `ts-loader` is used: https://github.com/1138-4EB/issue-runner/blob/master/webpack.config.js I believe this is a better 'real world' example.

> Maybe, the easiest way to solve this, is to just revert the change to pika, since this seems to be the root problem. The GitHub-SDK (octokit) is broken for a lot of people for nearly a week because of this.

It is possible to work around octokit being broken with https://github.com/1138-4EB/issue-runner/blob/40e659b7f6e0cca8125ac6e67d180a390fd5625b/.github/workflows/push.yml#L23-L25. It's an ugly fix, but it will let users to keep building actions/modules until this issue is properly fixed.

**Comment by gr2m** [comment] 2019-09-26 19:06
> Maybe, the easiest way to solve this, is to just revert the change to pika

I really don't want to do that, it's been a blessing to reduce the maintenance overhead. I'm still optimistic that we find a way around this and there are workarounds for the time being

**Comment by maplesteve** [comment] 2019-09-26 19:31
There is no workaround that „just works“ and patching distributed files of a sub-dependency is a no-go. Then at least release a version of octokit, that does this patching itself, so that we can use it again.

**Comment by gr2m** [comment] 2019-09-26 20:01
I do what I can Stephan.

**Comment by 1138-4EB** [comment] 2019-09-26 20:55
@gr2m I think that the main point is that adopting a tool which is less than a year old has broken a very broadly used package. This situation was reported 22 days ago, and it seems that it won't be fixed soon. From a professional point of view I think you should reconsider your position. Currently, potentially up to 28k project maintainers need to guess why their builds are failing, find this issue and apply an ugly and temporal solution. It is frustrating to read that you *don't want to* (i.e. prefer not to) fix it, although it seems that you know a way to do it now.

I understand that using pika is a blessing to reduce maintenance overhead and I am not arguing against. Nonetheless, I believe you can keep the migration to pika in a feature branch, revert the changes in master and then take your time to fix the issues with pika. It is not even clear yet if this is something to be fixed upstream.

The evolution of this issue is quite opposite of what is expected from a 'stable' tool. This is just some honest and constructive criticism; so, please, let us know how can we help you to have this issue fixed ASAP. We can then focus on enhancements and/or chores.

**Comment by gr2m** [comment] 2019-09-27 00:37
@1138-4EB  I know what to do. Have some patience. If you don't know how to temporarily patch (sub) dependencies without nasty hacks than please do some more research, it's really not that hard and will happen again earlier or later.

Please refrain from putting pressure on Open Source maintainers. I understand you are frustrated, but remember you are not entitled to anything. Please refrain from further commenting. I will update this issue as soon as there is a new version available.

**Comment by 1138-4EB** [comment] 2019-09-27 01:10
>  temporarily patch (sub) dependencies without nasty hacks

Which earlier commit do you recommend?

**Comment by gr2m** [comment] 2019-09-27 01:25
I like https://www.npmjs.com/package/patch-package

**Comment by FredKSchott** [comment] 2019-09-27 01:53
@1138-4EB in your  webpack example, can you try the `mainFields` fix proposed above?

 ```
module.exports = {
	entry: './dist/main.js',
	target: 'node',
	resolve: {
	  mainFields: ['main', 'module']
	}
	output: {
		path: join(__dirname, 'dist'),
		filename: 'main.pack.js'
	},
	optimization: {
		minimize: false
	},
	devtool: 'sourcemap'
};
```

**Comment by 1138-4EB** [comment] 2019-09-27 03:51
@FredKSchott, thanks for the suggestion! I tried https://github.com/1138-4EB/issue-runner/commit/be8dc20566780e557dcb11ebd0e9b730ed5bce27, but an error is produced when running webpack: https://github.com/1138-4EB/issue-runner/commit/be8dc20566780e557dcb11ebd0e9b730ed5bce27/checks#step:6:33

**Comment by travi** [comment] 2019-09-27 03:55
you might try working around the issue temporarily by marking it as an [external](https://webpack.js.org/configuration/externals/) in your webpack config. that would exclude it from the bundle and instead require it a runtime. not as ideal as everything going into the bundle, but should still work as long as `node_modules/` are still available in your runtime environment.

**Comment by 1138-4EB** [comment] 2019-09-27 04:15
@FredKSchott I now tried exactly the config you proposed (i.e. with a js file as an entry instead of a ts file): https://github.com/1138-4EB/issue-runner/commit/d7a7567b9ffd4af59d3b6de25bed5a7541973f40. I can confirm that it works. Compilation/build is successful, and execution too.

It is not ideal because I had to do a two-step build (first tsc, then webpack). Anyway, I consider this to be a negligible annoyance compared to not being able to build it. And it is definitely better than any other fix/patch suggested so far.

@travi, the *default* suggested workflow for js/ts GitHub Actions is to distribute a node_modules dir along with the main js file. I am precisely trying to avoid it. Should I need to keep `node_modules` for a single dep, I'd just run tsc and ignore webpack. Nonetheless, thanks for the suggestion; I will sure use it in other contexts.

**Comment by gr2m** [comment] 2019-10-06 16:00
Quick update: we are still looking into it.

@1138-4EB I have automated releases for my JavaScript-based actions which also use Octokit using semantic-release & ncc. I'm very happy with the setup, you can see it in action e.g. at https://github.com/gr2m/twitter-together/blob/master/.github/workflows/release.yml. I did not run into any of the problems discussed here

**Comment by 1138-4EB** [comment] 2019-10-06 16:09
@gr2m thanks for reporting! According to the comments in pikapkg/builders#90, the issue seems to be an unfortunate interaction with webpacks defaults only. Anyway the suggestion by @FredKSchott fixed the issue, so I can keep using https://github.com/1138-4EB/issue-runner/blob/master/webpack.config.js until this issue is fixed, until webpacks changes the defaults, or until I switch to a different packager.

**Comment by arlac77** [comment] 2019-10-06 17:35
For me the problem is that there is no way to select the node (none browser) content with a esm bundler (rollup).
If the default for this module sticks to the browser version (when using esm) i am lost (and all the other users of esm bundlers for none browser targets too)
@gr2m maybe the decision of providing the browser version behind the package "module" entry should be reflected

**Comment by gr2m** [comment] 2019-10-06 17:45
rollup has a setting just like webpack which allows you to prefer "main" over "module" package key for builds with node target.

**Comment by arlac77** [comment] 2019-10-06 18:16
@gr2m shure but this is a global rollup config decision. I would rather like it the other way around and explicitly use the "browser" option of rollup-plugin-node-resolve

```
// some package.json files have a "browser" field which specifies
      // alternative files to load for people bundling for the browser. If
      // that's you, either use this option or add "browser" to the
      // "mainfields" option, otherwise pkg.browser will be ignored
      browser: true,  // Default: false
```

**Comment by gr2m** [comment] 2019-10-06 18:18
I understand your preference, but it's not going to happen any time soon, your use case is the edge case here.

**Comment by arlac77** [comment] 2019-10-06 18:35
@gr2m isn't the purpose of "universal-user-agent" to provide a user agent for none browser applications too ? shouldn't node applications be in the main focus (there the need for a user agent is higher than in the browser) ?

As shown in [universal-user-agent-bundler-problems](https://github.com/arlac77/universal-user-agent-bundler-problems) doesn't work for the minimal rollup bundling (none browser) use case

**Comment by gr2m** [comment] 2019-10-06 18:47
Node apps work perfectly fine, because node apps respect the "main" key. The "module" key is not used by Node it won't be in future as things state right now, the problem here are build tools with node as a target, which is an edge case compared to building for browsers.

I'm still looking into making it work, but there is a lot to consider. And the build problems for node can be worked around so there is no rush.

**Comment by arlac77** [comment] 2019-10-06 19:20
@gr2m even without bundling "universal-user-agent" can`t be used from node as a es6 module

So then please correct your README example and remove the import variant or state that the module is browser only (which then cascades to all the @octokit modules too)

```js index.mjs
import { getUserAgent } from "universal-user-agent";

console.log(getUserAgent());
```

```sh
node --experimental-modules index.mjs
```

```
file:///Users/markus/build/universal-user-agent-bundler-problems/index.mjs:1
import { getUserAgent } from "universal-user-agent";
         ^^^^^^^^^^^^
SyntaxError: The requested module 'universal-user-agent' does not provide an export named 'getUserAgent'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:93:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:108:20)
    at async Loader.import (internal/modules/esm/loader.js:137:24)
mbpMarkus:universal-user-agent-bundler-problems markus$ cat index.mjs 
```

**Comment by gr2m** [comment] 2019-10-06 19:29
I’ve said all there is to say. I recommend you do some research about the state of ES modules in Node. 

I’ll add further comments when I have any update

**Comment by arlac77** [comment] 2019-10-06 20:13
The problem has nothing to do with ES modules itself, only with the selection between node or browser content.
I don't see any solution from node side all they are working on is improving the esm experience.
The authors an consumers of packages together have to find a way to select between both worlds
(that's why someone invented the browser field)

**Comment by arlac77** [comment] 2019-10-06 20:24
@gr2m the official npm doc also mentions the browser field

[browser](https://docs.npmjs.com/files/package.json#browser)

**Comment by arlac77** [comment] 2019-10-07 19:52
Her another type of workaround:
replacing the whole module with one line of code during bundling (for node runtime only).


_rollup.config.js_
```js
import virtual from "rollup-plugin-virtual";
...

    plugins: [
      virtual({
        "universal-user-agent":
          "export function getUserAgent() {return `Node.js/${process.version.substr(1)} (${process.platform}); ${process.arch})`}"
      }),
      ...otherPlugins
    ]
```

**Comment by arlac77** [comment] 2019-10-15 11:30
@gr2m there is a recently updated proposal for _Conditional Mapping_ in packages
[jkrems/proposal-pkg-exports](https://github.com/jkrems/proposal-pkg-exports#2-conditional-mapping)

**Comment by gr2m** [comment] 2019-10-15 21:43
Thanks I'm following it closely, relevant discussion is here: https://github.com/nodejs/modules/issues/401

**Comment by eamodio** [comment] 2019-11-19 23:50
Does anyone know of a way to workaround this (other than editing the `package.json`) with webpack (also without using `resolve.mainFields` because that affects all modules). I am trying to use `octokit/code` in 2 of my VS Code extensions and because I use ES modules (mainly for tree-shaking) this breaks the bundling.

I've tried using
```
alias: {
	'universal-user-agent': 'node_modules/universal-user-agent/dist-node/index.js'
}
```

But that causes other `Module not found: Error: Can't resolve 'universal-user-agent'` in other octokit dependencies.

**Comment by gr2m** [comment] 2019-11-20 21:16
There is no ESM version of `universal-user-agent` for Node right now, sorry. The ESM version is for browsers, Node only has a CJS version. Because Node didn't support ESM until very recently.

I've worked with Node's ES Modules working group over the past weeks and there is a clear way forward now. It will take some time for the build tools and Pika to catch up, but Node's latest spec supports all that we need: https://github.com/nodejs/node/blob/master/doc/api/esm.md

The package.json will look like this:

```js
{
  "main": "dist-node-cjs/index.js",
  "module": {
    "browser": "dist-browser/index.js"
    "default": "dist-node/index.js"
  }
}
```

Once the tooling catches up, I'll update the library. Shouldn't take too long, it's mostly Pika and its Rollup plugins, and Fred from Pika has been involved in the same working group.

**Comment by nonoroazoro** [comment] 2019-12-11 08:38
Fixed by adding the following alias in webpack configuration as always.

```json
alias: {
            "universal-user-agent$": "universal-user-agent/dist-node/index.js
}
```

**Comment by sheepsteak** [comment] 2019-12-31 17:00
I've managed to use Webpack's `NormalModuleReplacementPlugin` to point Webpack to the correct entry point for my Serverless service:

```js
plugins: [
  new webpack.NormalModuleReplacementPlugin(
      /universal-user-agent\/dist-web\/index\.js/,
      "../dist-src/index.js"
    )
]
```

I used `dist-src` as it still uses modules whereas `dist-node` is CommonJS.

**Comment by KamasamaK** [comment] 2020-02-17 18:22
The above workaround with `NormalModuleReplacementPlugin` did not work for me, but this did:
```js
resolve: {
  // ...
  alias: {
    "universal-user-agent": path.resolve(
      __dirname,
      "node_modules/universal-user-agent/dist-src/index.js"
    )
  }
}
```

**Comment by gr2m** [comment] 2020-02-21 18:27
I'll add a try/catch around the `navigator.userAgent`, so at least it should no longer throw an error, via https://github.com/gr2m/universal-user-agent/pull/41

Once conditional exports are supported by `@pika/pack`, I can provide custom exports for different environments, so the resulting user agent will be more helpful than `<navigator unknown>`, but at least this should unblock people for the time being

Any thoughts?

**Comment by gr2m** [comment] 2020-05-12 20:14
I've decided to greatly simplify this package to workaround the build problems y'all are experiencing. I was hoping for conditional exports to be adopted more quickly, but it does not look like it.

See https://github.com/gr2m/universal-user-agent/issues/52

**Closed** 2020-07-16 19:45 UTC

**Comment by RubyRedcode** [comment] 2021-05-22 04:19
> I've managed to use Webpack's `NormalModuleReplacementPlugin` to point Webpack to the correct entry point for my Serverless service:
> 
> ```js
> plugins: [
>   new webpack.NormalModuleReplacementPlugin(
>       /universal-user-agent\/dist-web\/index\.js/,
>       "../dist-src/index.js"
>     )
> ]
> ```
> 
> I used `dist-src` as it still uses modules whereas `dist-node` is CommonJS.

https://github.com/gr2m/universal-user-agent/issues/23#issuecomment-569959072
